version: '3'
services:
  db:
    build: 
        context: .
        dockerfile: ./DockerFileDB    
    ports:
      - "5250:3306"
    volumes:
      - datavolume:/var/lib/mysql
    container_name: ApolloDB
    environment:
      MYSQL_ROOT_PASSWORD: 1234

     
  restapi:
    container_name: ApolloREST
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://localhost:80/;
    ports:
        - "5200:80"
        - "5204:443"
    build:
        context: .
        dockerfile: ./DockerFileWeb
    links:
        - db
      
volumes:
    datavolume:
