version: '2'
services:
  db:
    build: .    
    ports:
      - "3306:3306"
    volumes:
      - datavolume:/var/lib/mysql
    container_name: test-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    container_name: ApolloPhpmyadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: 1234
    ports:
        - 3000:80
    links:
        - db
        
  dotnetcore:
    container_name: ApolloDevDotnet
    build:
        context: ../.devcontainer
        dockerfile: ./Dockerfile        
        args:  
            #Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1
            VARIANT: "3.1"
            
            #Options
            INSTALL_NODE: "false"
            NODE_VERSION: "lts/*"
            INSTALL_AZURE_CLI: "false"

    command: sleep infinity
    volumes:
        - ..:/workspace:cached
    network_mode: service:db
      
volumes:
  datavolume: